# Generated by Django 3.2.25 on 2024-07-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cuisine', models.CharField(blank=True, max_length=100, null=True)),
                ('difficulty', models.CharField(blank=True, max_length=50, null=True)),
                ('dietary_restrictions', models.CharField(blank=True, max_length=255, null=True)),
                ('nutritional_info', models.JSONField(blank=True, null=True)),
                ('ingredient_list', models.TextField()),
                ('instructions', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('reviews', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
