# Generated by Django 3.2.25 on 2024-07-22 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=100)),
                ('trend_score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SEOAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_score', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seo_analytics', to='recipe_management.recipe')),
            ],
        ),
    ]
