# Generated by Django 3.2.25 on 2024-07-22 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipe_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CulinaryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=255, null=True)),
                ('content_type', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LocalCuisineSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('cuisine_type', models.CharField(max_length=100)),
                ('suggested_recipes', models.ManyToManyField(related_name='local_cuisine_suggestions', to='recipe_management.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='AugmentedRealityKitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_data', models.JSONField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='augmented_reality_kitchens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
